# Testing functions

## testing g(.)
```{r}
lambda <- 5/2
l <- 1
ltrans <- sqrt(2 * lambda) / l
xik <- 3
xjk <- 11
# see comments in r(., .)
```

## tests for covMatrix()
```{r}
## n > 2
set.seed(761)
n <- 3
X <- matrix(rnorm(n^2), ncol = n)
sig2 <- 1
l <- rep(1, n)

covMatrix(X = X, sig2 = sig2, covar.fun = r.matern, l = l)
#            [,1]        [,2]        [,3]
# [1,] 1.00000000 0.282701688 0.033777719
# [2,] 0.28270169 1.000000000 0.004503518
# [3,] 0.03377772 0.004503518 1.000000000

covMatrix(X = X, sig2 = sig2, covar.fun = r.matern2, l = l)
#             [,1]         [,2]         [,3]
# [1,] 1.000000000  0.033252107  0.009911215
# [2,] 0.033252107  1.000000000 -0.001770277
# [3,] 0.009911215 -0.001770277  1.000000000
```

```{r}
## test covMatrix with X and X2
set.seed(761)
d <- 3
n <- 3
n2 <- 5
X <- matrix(rnorm(n * d), ncol = d)
X2 <- matrix(rnorm(n2 * d), ncol = d)
sig2 <- 1
l <- rep(1, d)

Sxx2 <- covMatrix(X = X, X2 = X2, sig2 = sig2, covar.fun = r.matern, l = l)
#            [,1]       [,2]        [,3]        [,4]       [,5]
# [1,] 0.04502962 0.15642754 0.062580665 0.013177028 0.62083778
# [2,] 0.02878820 0.54686770 0.003686774 0.004360299 0.24965378
# [3,] 0.16288193 0.01292614 0.132912144 0.039424313 0.08737432

check <- covMatrix(X = rbind(X, X2), sig2 = sig2, covar.fun = r.matern, l = l)
check[1:n, (d+1):ncol(check)]  # should match above 

# check transpose
Sx2x <- covMatrix(X = X2, X2 = X, sig2 = sig2, covar.fun = r.matern, l = l)
all.equal(Sxx2, t(Sx2x))

# check for derivative 
Sxx2 <- covMatrix(X = X, X2 = X2, sig2 = sig2, covar.fun = r.matern2, l = l)
#              [,1]          [,2]          [,3]        [,4]        [,5]
# [1,] -0.002102069  0.0004978479 -0.0003179733 0.004930518 0.742774647
# [2,]  0.006641330  0.4612068552  0.0005814886 0.013433604 0.078784734
# [3,]  0.017223647 -0.0014741390  0.0177985685 0.001978487 0.004885587

Sx2x <- covMatrix(X = X2, X2 = X, sig2 = sig2, covar.fun = r.matern2, l = l)
```


## testing whether errors are thrown correctly
```{r}
set.seed(761)
n <- 3
X <- matrix(rnorm(n^2), ncol = n)
sig2 <- 1
l <- rep(1, n)

# no l or ltrans argument
covMatrix(X = X, sig2 = sig2, covar.fun = r.matern)  
 # Error in { : 
 #  task 1 failed - "Length scale parameter l or ltrans missing." 
# - hooray and we know exactly what's wrong due to error handling in r.matern
```



```{r}
## n = 2
set.seed(761)
n <- 2
X <- matrix(rnorm(n^2), ncol = n)
sig2 <- 1
l <- rep(1, n)

## before creating covar.fun argument
# test <- covMatrix(X = X, sig2 = sig2, l = l)
# test
#           [,1]      [,2]
# [1,] 1.0000000 0.5694542
# [2,] 0.5694542 1.0000000

## after creating covar.fun argument
covMatrix(X = X, sig2 = sig2, covar.fun = r.matern, l = l)
#           [,1]      [,2]
# [1,] 1.0000000 0.5694542
# [2,] 0.5694542 1.0000000
```

# function arguments
```{r}
tmp <- rnorm
do.call(what = tmp, args = list(n = 10, mean = 5))

tmp <- function(...) {
  do.call(what = rnorm, args = list(...))
}

tmp(n = 10, mean = 5)
```


# trying to understand the Matern covariance
```{r}
xi <- 0
xj <- seq(0, 10, length.out = 100)
covar.vals <- NULL
for (i in 1:length(xj)) {
  covar.vals <- c(covar.vals, r(xi = xi, xj = xj[i], l = 1))
}
plot(x = abs(xi - xj), y = covar.vals, pch = 16)

## squared exponential 
```

# testing mvn sampler + density 
```{r}
library(Matrix); library(mvtnorm)
randomCov <- function(n) {
  L <- matrix(0, nrow = n, ncol = n)
  L[lower.tri(L)] <- rnorm(sum(lower.tri(L)))
  diag(L) <- abs(rnorm(length(diag(L))))
  
  return(L %*% t(L))
}

set.seed(361)
n <- 100
S <- randomCov(n = n) + diag(rep(1e-9, n)) #as.matrix(Hilbert(n))
Sev <- eigen(S)$values
which(Sev <= 0) # check positive definite (want all positive eigenvalues)
m <- rep(3, n)
y <- rmvnorm(1, mean = m, sigma = S)
rmvnorm(1, m, S)

## check density
dmvnorm(m, mean = m, sigma = S, log = F)
dmvn(m, m, S, log = F)

## compare speed
library(microbenchmark)

microbenchmark(dmvnorm(m, mean = m, sigma = S, log = F),
                          dmvn(m, m, S, log = F), times = 1000)

microbenchmark(rmvnorm(1, mean = m, sigma = S, method = "chol"),
               rmvn(1, m, S), times = 100000)


#' - so... mvtnorm  is faster + didn't need to add the nugget (no complaints)
#' - no need to use mine then
#' - sampling more than 1 is faster with method = "chol"
# > microbenchmark(rmvnorm(1, mean = m, sigma = S, method = "chol"),
# +                rmvn(1, m, S), times = 100000)
# Unit: microseconds
#                                              expr     min      lq     mean  median       uq       max neval
#  rmvnorm(1, mean = m, sigma = S, method = "chol") 416.813 502.207 670.4624 531.482 564.2635  88332.79 1e+05
#                                     rmvn(1, m, S) 346.407 427.730 594.6084 453.745 484.1735 128485.16 1e+05


## check sampler
#rmvn(3, m, S)  # expect 3 x length(m) matrix

```


# eta0 small tests

## testing log.posterior
```{r}
post.args <- list(l = 5.7,  # 5.7
                  sig2 = 1500,
                  ystar = ytrue(xstar),
                  yprime = 20 / (20 * xprime),
                  given = given)

do.call(logposterior, post.args)  # -6080.763
```

```{r}
l <- 15
sig2 <- 1
ystar <- ytrue(xstar)
yprime <- 20 / (20 * xprime)
given <- given
```

## find starting l, sig2 values
```{r}
## run setup

# monotone increasing function
ytrue <- function(x) {log(20*x + 1)}  # x > -1/20

# inputs where fcn evaluated
x <- cbind(c(0, 0.1, 0.2, 0.3, 0.4, 0.9, 1))
# true/known model values
y <- ytrue(x)

# prediction set inputs
xstar <- cbind(seq(0, 1, length.out = 50))

# derivative set inputs
xprime <- cbind(c(0.42, 0.47, 0.52, 0.57, 0.62, 0.67, 0.72, 0.77, 0.82, 0.87))

given <- list(x = cbind(x), xprime = cbind(xprime), xstar = cbind(xstar),
              y = y)

l <- seq(5.5, 6, length.out = 5)
sig2 <- seq(1450, 1550, length.out = 10)
grid <- expand.grid(l, sig2)

testpost <- function(l.sig2) {
  res <- logposterior(l = l.sig2[1], sig2 = l.sig2[2], ystar = ytrue(xstar),
               yprime = 20 / (20 * xprime),
               given = given)
  cat(l.sig2, ":", res, "\n")
  return(res)
}

probs <- apply(grid, MARGIN = 1, FUN = testpost)
ord <- cbind(grid, probs)
ord <- ord[order(probs, decreasing = TRUE),]
candidates <- rbind(candidates, ord[1,])
ord
```

```{r}
candidates
```

